### ISSUE TITLE
About Superpixel Landmarks

### ISSUE THREAD

**Issue by ShichenLiu** [YangZhang4065/AdaptationSeg#11]
Hi Yang,

The code of your paper is elegant and easy to reproduce. But where can I find the code to train the multi-class SVM that yields the superpixel annotations of the target domain? Thanks!

**Comment by YangZhang4065** [comment]
Hi @ShichenLiu ,

Sorry for the late reply as GitHub does not notify me the issue.

I apologize for the inconvenience. The code to annotate each image on superpixel-level is not published as it has not been organized yet. And the process involved multiple codes in both MATLAB and python.
