### ISSUE TITLE
Class-wise evaluation IoU

### ISSUE THREAD

**Issue by dagdelenmustafa** [YangZhang4065/AdaptationSeg#18]
Hi @YangZhang4065 ,
Thank you so much for your study. I could train and evaluate your code but I couldn't achieve class wise evaluation IoUs with `test_FCN_DA.py`. How could I get these metrics ? Thank you.

**Comment by YangZhang4065** [comment]
Hi @dagdelenmustafa ,

Sorry I missed your issue earlier. Have you been able to solve the problem?

**Comment by dagdelenmustafa** [comment]
Hi, unfortunately i couldn't handle this problem. But there is no need any more, i prepared and submitted my survey about domain adaptation. Thank you again. Maybe for the future comers your answer could be useful.
